### PR TITLE
Fix auto increment bug

### LINKED ISSUE #19: Fix increment doubling issue when seeding data

### PR DESCRIPTION
**Pull request by cagallo**
## What Features are Being Added?

- None

## What is Being Refactored?

- Refactor table seeding to restart auto increment back to 1 when `knex seed:run` happens

## Where should the reviewer start?

- seeds/books_favorites.js

## How should this be manually tested?

- run `knex seed:run` 
- check favorites table

## What are the relevant tickets?

- Fix auto increment bug when seeding data tables

## Any Other Notes/Questions/Problems?

- None at the moment!

### CODE REVIEW

File: db/seeds/books_favorites.js [hunk 1]
```diff
@@ -9,6 +9,18 @@ exports.seed = function(knex) {
   // Deletes ALL existing entries
     return knex('books').del()
     .then(() => {
-      return knex('books').insert(booksData)
+      return knex.raw('ALTER SEQUENCE books_id_seq RESTART WITH 1');
```
Comment (krdurrett) [inline db/seeds/books_favorites.js:12]: This is a great help to fix the auto increment reset

**Review by krdurrett — APPROVED** [review]
Great job fixing the auto-increment bug fix
